### ISSUE TITLE
possible to spawn many processes ?

### ISSUE THREAD

**Issue by gedw99** [crawshaw/littleboss#8]
Is it possible for the supervisor to manage many child processes ?

Also i presume it does NOT work on windows ?

**Comment by crawshaw** [comment]
One littleboss per service. You can have more than one. A service can have its own children if you have a process-group, but it's one entity to the supervisor.

Conceptually littleboss could work on windows, but doesn't today because the implementation uses unix domain sockets. It might work out of the box on the linux-on-windows thing, WSL, I haven't tried.

**Comment by crawshaw** [comment]
(I'm going to close this, as I'm not sure how to use GitHub issues for questions. If you have more questions, ask away.)

**Comment by gedw99** [comment]
It's cool. I was expecting it to not work on windows - just wanted to make
sure
